apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubeflow-secrets
  namespace: kubeflow
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /secrets
    match:
    - uri:
        exact: /secrets
    - uri:
        prefix: /secrets/
    rewrite:
      uri: /
    route:
    - destination:
        host: kubeflow-secrets.kubeflow.svc.cluster.local
        port:
          number: 80
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: kubeflow-secrets
  namespace: kubeflow
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
        - cluster.local/ns/istio-system/sa/istio-ingressgateway
        - cluster.local/ns/kubeflow/sa/centraldashboard
  selector:
    matchLabels:
      app: kubeflow-secrets
