apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-web-app
rules:
- apiGroups: ["kubeflow.org"]
  resources: ["profiles"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["users", "groups", "serviceaccounts"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-web-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-web-app
subjects:
- kind: ServiceAccount
  name: secrets-web-app
  namespace: kubeflow
