apiVersion: v1
kind: Service
metadata:
  name: kubeflow-secrets
  namespace: kubeflow
  labels:
    app: kubeflow-secrets
spec:
  selector:
    app: kubeflow-secrets
  ports:
  - name: http
    port: 80
    targetPort: http
